### ISSUE TITLE
autocomplete doesn't escape item text before passing to regex

### ISSUE THREAD

**Issue by rosslavery** [Promact/md2#183]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Autocomplete filtering should work with items that contain regex characters. For example:
```Canadian Dollars (CAD)```

#### What is the current behavior?
Throws  w/ error:
```
Subscriber.js:240 Uncaught SyntaxError: Invalid regular expression: /Canadian Dollars (CAD/: Unterminated group
    at RegExp (<anonymous>)
    at http://localhost:4200/vendor.bundle.js:86305:140
    at Array.filter (native)
    at Md2Autocomplete.updateItems (http://localhost:4200/vendor.bundle.js:86305:111)
    at http://localhost:4200/vendor.bundle.js:86225:27
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:10923:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:4327:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:10922:36)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:10690:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:10985:38)
    at timer (http://localhost:4200/polyfills.bundle.js:12065:29)
```

#### What are the steps to reproduce?
Pass items w/ regex-ey characters to the autocomplete items input.

#### Which versions of Angular, MD2, OS, browsers are affected?
md2 0.0.19
angular 4.0.3

**Comment by dharmeshpipariya-zz** [comment]
@rosslavery our plunkr template is available on -> http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info you can use it for creating an issue.
