### ISSUE TITLE
Tab Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by ghost** [Promact/md2#211]
#### Bug
In IE there is an error when I use Tab, I  used md2 with Ionic3
Runtime Error
Object doesn't support property or method 'forEach'
Stack
TypeError: Object doesn't support property or method 'forEach'
   at Md2Tabs.prototype.updatePagination (http://localhost:8100/build/main.js:161489:9)
   at Anonymous function (http://localhost:8100/build/main.js:161374:13)
   at t.prototype.invokeTask (http://localhost:8100/build/polyfills.js:3:9048)
   at onInvokeTask (http://localhost:8100/build/main.js:4419:21)
   at t.prototype.invokeTask (http://localhost:8100/build/polyfills.js:3:9048)
   at r.prototype.runTask (http://localhost:8100/build/polyfills.js:3:4323)
   at invoke (http://localhost:8100/build/polyfills.js:3:10123)
   at e (http://localhost:8100/build/polyfills.js:2:28104)
Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: ^4.1.3
Angular Compiler CLI: ^4.1.3
Node: 6.10.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by gongycn** [comment]
I have found the solution about this question, following the steps below:
1. find files `node_modules\md2\bundles\md2.umd.js` and `node_modules\md2\tabs\tabs.js`;
2. change method `Md2Tabs.prototype.updatePagination` to 
```javascript
Md2Tabs.prototype.updatePagination = function () {
    var canvasWidth = this.element.root.clientWidth;
    if(!!this.element.tabs.forEach){
        this.element.tabs.forEach(function (tab) {
            canvasWidth -= tab.offsetWidth;
        });
    }
    this._shouldPaginate = canvasWidth < 0;
};
```
but it's not a good solution.
