### ISSUE TITLE
Angular CLI Issue

### ISSUE THREAD

**Issue by adamRiddy** [Promact/md2#65]
I had this library working fine using systemjs . I had to move to web pack and I get the following error 

webpack: bundle is now VALID
/Users/ar/Programs/angCLI/CashPanda/node_modules/md2/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './core';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ar/Programs/angCLI/CashPanda/dist/server/server.bundle.js:2212:18)
    at __webpack_require__ (/Users/ar/Programs/angCLI/CashPanda/dist/server/server.bundle.js:21:30)

The module definition is

import { Md2Module }  from 'md2';
import { MdCardModule } from '@angular/material';

@NgModule({
  imports: [
    CommonModule, Md2Module.forRoot(), MdCardModule.forRoot()
  ],
  declarations: [FaqsComponent],
  exports: [FaqsComponent]
})
export class FaqsModule { }

Everything has been installed with npm install md2 --save

Can you create an example with the Angular 2 CLI?

Thanks in advance for your help.

**Comment by dharmeshpipariya-zz** [comment]
@adamRiddy We have fixed the issue with release md2@0.0.14,
comment here if you have an issue

**Comment by adamRiddy** [comment]
Hi Dharmesh,
	Thanks for looking at this. I will retest next week.
Regards,
Adam.

Adam Riddy
e-mail: adam@selectionpoint.co.uk <mailto:eli@selectionpoint.co.uk>
